workflow

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -80,54 +80,53 @@ jobs:
           - i686-unknown-linux-musl
 
         steps:
-        - name: Checkout repository
-          uses: actions/checkout@v4
-          with:
-            repository: sockheadrps/rpaudio
-            token: ${{ secrets.GITHUB_TOKEN }}
-
-        - name: Set up Python 3.9
-          uses: actions/setup-python@v4
-          with:
-            python-version: 3.9
-
-        - name: Install Rust and Cargo
-          run: |
-            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
-            source $HOME/.cargo/env
-
-        - name: Upgrade pip and install maturin
-          run: |
-            python -m pip install --upgrade pip
-            python -m pip install maturin
-            
-            # Ensure maturin is in PATH
-            export PATH="$HOME/.cargo/bin:$PATH"
-            echo "PATH=$PATH"
-            which maturin || { echo "Maturin not found in PATH"; exit 1; }
-      
-            # Build the wheel
-            maturin build --release --out /tmp/dist -m Cargo.toml || { echo "Maturin build failed"; exit 1; }
-      
-            # Check if /tmp/dist contains files
-            ls /tmp/dist || { echo "No files in /tmp/dist"; exit 1; }
-      
-            # Create the /io/dist directory if it doesn't exist
-            mkdir -p /io/dist/
-      
-            # Move the output files back into the GitHub workspace for later steps or artifacts
-            mv /tmp/dist/* /io/dist/ || { echo "Failed to move files"; exit 1; }
-
-        - name: Install built wheel
-          run: |
-            python -m pip install /io/dist/rpaudio-0.0.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl --force-reinstall
-            python -c "import rpaudio"
-
-        - name: Upload Wheels
-          uses: actions/upload-artifact@v3
-          with:
-            name: wheels
-            path: /io/dist
+          - name: Checkout repository
+            uses: actions/checkout@v4
+            with:
+              repository: sockheadrps/rpaudio
+              token: ${{ secrets.GITHUB_TOKEN }}
+    
+          - name: Set up Python 3.9
+            uses: actions/setup-python@v4
+            with:
+              python-version: 3.9
+    
+          - name: Install Rust and Cargo
+            run: |
+              curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+              source $HOME/.cargo/env
+    
+          - name: Upgrade pip and install maturin
+            run: |
+              python -m pip install --upgrade pip
+              python -m pip install maturin
+               # Ensure maturin is in PATH
+              export PATH="$HOME/.cargo/bin:$PATH"
+              echo "PATH=$PATH"
+              which maturin || { echo "Maturin not found in PATH"; exit 1; }
+        
+              # Build the wheel
+              maturin build --release --out /tmp/dist -m Cargo.toml || { echo "Maturin build failed"; exit 1; }
+        
+              # Check if /tmp/dist contains files
+              ls /tmp/dist || { echo "No files in /tmp/dist"; exit 1; }
+        
+              # Create the /io/dist directory if it doesn't exist
+              mkdir -p /io/dist/
+        
+              # Move the output files back into the GitHub workspace for later steps or artifacts
+              mv /tmp/dist/* /io/dist/ || { echo "Failed to move files"; exit 1; }
+    
+          - name: Install built wheel
+            run: |
+              python -m pip install /io/dist/rpaudio-0.0.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl --force-reinstall
+              python -c "import rpaudio"
+    
+          - name: Upload Wheels
+            uses: actions/upload-artifact@v3
+            with:
+              name: wheels
+              path: /io/dist
 
   linux-cross:
     runs-on: ubuntu-latest
