Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -9,46 +9,46 @@ on:
       - 'v*'
 
 jobs:
- check-output-date:
-  name: Check pytest output date
-  runs-on: ubuntu-latest
-  steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+  check-output-date:
+    name: Check pytest output date
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-    - name: Check output date
-      run: |
-        # Extract the last line containing the time
-        last_line=$(tail -n 4 pytest_output.txt | head -n 1)
+      - name: Check output date
+        run: |
+          # Extract the last line containing the time
+          last_line=$(tail -n 4 pytest_output.txt | head -n 1)
 
-        # Extract the time from the last line
-        pytest_time=$(echo "$last_line" | grep -oP "\d{2}:\d{2}:\d{2}")
-        
-        # Get the current date in UTC
-        today=$(date -u +%Y-%m-%d)
-        now=$(date -u +%s)
+          # Extract the time from the last line
+          pytest_time=$(echo "$last_line" | grep -oP "\d{2}:\d{2}:\d{2}")
+          
+          # Get the current date in UTC
+          today=$(date -u +%Y-%m-%d)
+          now=$(date -u +%s)
 
-        # Combine current date with extracted time
-        datetime="$today $pytest_time"
-        
-        # Convert combined datetime to Unix timestamp in UTC
-        pytest_timestamp=$(date -u -d "$datetime" +%s 2>/dev/null)
-        if [ $? -ne 0 ]; then
-          echo "Error: Invalid date or time format"
-          exit 1
-        fi
+          # Combine current date with extracted time
+          datetime="$today $pytest_time"
+          
+          # Convert combined datetime to Unix timestamp in UTC
+          pytest_timestamp=$(date -u -d "$datetime" +%s 2>/dev/null)
+          if [ $? -ne 0 ]; then
+            echo "Error: Invalid date or time format"
+            exit 1
+          fi
 
-        echo "Pytest timestamp: $pytest_timestamp"
-        one_hour_ago=$(($now - 3600))
+          echo "Pytest timestamp: $pytest_timestamp"
+          one_hour_ago=$(($now - 3600))
 
-        # Print one hour ago timestamp
-        echo "One hour ago timestamp: $one_hour_ago"
+          # Print one hour ago timestamp
+          echo "One hour ago timestamp: $one_hour_ago"
 
-        # Check if pytest_timestamp is older than one hour
-        if [ "$pytest_timestamp" -lt "$one_hour_ago" ]; then
-          echo "Pytest output is outdated or not from today. Please run the tests again."
-          exit 1
-        fi
+          # Check if pytest_timestamp is older than one hour
+          if [ "$pytest_timestamp" -lt "$one_hour_ago" ]; then
+            echo "Pytest output is outdated or not from today. Please run the tests again."
+            exit 1
+          fi
 
   windows:
     runs-on: windows-latest
